using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TM_PE.Data;
using TM_PE.Model;

namespace TM_PE.Pages.OfficeTask
{
    public class CreateModel : PageModel
    {
        // TODO: replace ApplicationDbContext with your actual DbContext class name if different
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Model.OfficeTask OfficeTask { get; set; } = new();

        // Populated via hidden inputs generated by JS as employees are added
        [BindProperty]
        public List<int> SelectedEmployeeIds { get; set; } = new();

        // Populated via hidden inputs generated by JS as activities are added
        [BindProperty]
        public List<string> Activities { get; set; } = new();

        // Used to populate the "Assign Employees" dropdown
        public List<Employee> EmployeeList { get; set; } = new();

        public async Task OnGetAsync()
        {
            EmployeeList = await _context.Employees
                .OrderBy(e => e.FullName) // adjust to match your Employee model's name property
                .ToListAsync();

            OfficeTask.DateCreated = DateTime.Now;
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // TaskNumber is auto-generated server-side, so don't require it on post
            ModelState.Remove("OfficeTask.TaskNumber");

            SelectedEmployeeIds ??= new();
            Activities ??= new();

            if (!SelectedEmployeeIds.Any())
                ModelState.AddModelError(string.Empty, "Please assign at least one employee.");

            if (!Activities.Any())
                ModelState.AddModelError(string.Empty, "Please add at least one activity.");

            if (!ModelState.IsValid)
            {
                EmployeeList = await _context.Employees
                    .OrderBy(e => e.FullName)
                    .ToListAsync();
                return Page();
            }

            OfficeTask.TaskNumber = await GenerateTaskNumberAsync();
            OfficeTask.Status = "Pending";
            OfficeTask.Progress = 0;

            _context.OfficeTasks.Add(OfficeTask);
            await _context.SaveChangesAsync(); // generates OfficeTask.OfficeTaskID

            foreach (var employeeId in SelectedEmployeeIds)
            {
                _context.TaskAssignments.Add(new TaskAssignment
                {
                    OfficeTaskID = OfficeTask.OfficeTaskID,
                    EmployeeID = employeeId,
                    AssignedDate = DateTime.Now
                });
            }

            foreach (var activityName in Activities)
            {
                _context.TaskActivities.Add(new TaskActivity
                {
                    OfficeTaskID = OfficeTask.OfficeTaskID,
                    ActivityName = activityName,
                    Status = "Pending",
                    DateCreated = DateTime.Now
                });
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("Index");
        }

        private async Task<string> GenerateTaskNumberAsync()
        {
            var count = await _context.OfficeTasks.CountAsync();
            return $"TASK-{DateTime.Now:yyyy}-{(count + 1):D4}";
        }
    }
}
