using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.EntityFrameworkCore;
using TM_PE.Data;
using TM_PE.Model;

namespace TM_PE.Pages.Manager.JobTickets
{
    public class CreateModel : PageModel
    {
        private readonly AppDbContext _context;

        public CreateModel(AppDbContext context)
        {
            _context = context;
        }

        [BindProperty]
        public Model.JobTicket JobTicket { get; set; } = new();

        // Populated via hidden inputs generated by JS as field technicians are added
        [BindProperty]
        public List<int> SelectedEmployeeIds { get; set; } = new();

        // The single employee (must be one of SelectedEmployeeIds) marked as the leader
        [BindProperty]
        public int LeaderEmployeeId { get; set; }

        // Used to populate the "Add Assignees" dropdown — Field Technicians only
        public List<Employee> FieldTechnicianList { get; set; } = new();

        // Read-only preview of the ticket number that will be generated on save
        public string NextTicketNumber { get; set; } = string.Empty;

        public int[] FiberPlanOptions { get; set; } = FiberPlans.Allowed;

        public string[] JobTypeOptions { get; set; } = JobTypes.Allowed;

        public async Task OnGetAsync()
        {
            FieldTechnicianList = await _context.Employees
                .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician)
                .OrderBy(e => e.FullName)
                .ToListAsync();

            JobTicket.DateCreated = DateTime.Now;
            JobTicket.ServiceDate = DateTime.Now;
            NextTicketNumber = await GenerateTicketNumberAsync();
        }

        public async Task<IActionResult> OnPostAsync()
        {
            // Auto-generated / hidden fields shouldn't be required on postback validation
            ModelState.Remove("JobTicket.TicketNumber");
            ModelState.Remove("JobTicket.Status");
            // FiberPlan/Description are conditionally required depending on JobType,
            // so their built-in validation attributes are skipped in favor of manual checks below.
            ModelState.Remove("JobTicket.FiberPlan");
            ModelState.Remove("JobTicket.Description");
            // Client Full Name / Primary / Secondary Number are only collected for
            // non-Maintenance jobs, so their built-in [Required] attributes are skipped
            // in favor of the manual, JobType-aware checks below.
            ModelState.Remove("JobTicket.ClientFullName");
            ModelState.Remove("JobTicket.PrimaryNumber");
            ModelState.Remove("JobTicket.SecondaryNumber");

            SelectedEmployeeIds ??= new();

            if (!JobTypes.Allowed.Contains(JobTicket.JobType))
                ModelState.AddModelError("JobTicket.JobType", "Please select a valid job type.");

            if (JobTicket.ServiceDate.Date < DateTime.Now.Date)
                ModelState.AddModelError("JobTicket.ServiceDate", "Date cannot be set to a previous day.");

            if (JobTicket.JobType == JobTypes.Installation)
            {
                if (JobTicket.FiberPlan == null || !FiberPlans.Allowed.Contains(JobTicket.FiberPlan.Value))
                    ModelState.AddModelError("JobTicket.FiberPlan", "Please select a valid fiber plan.");

                JobTicket.Description = null;
            }
            else if (JobTicket.JobType == JobTypes.Repair || JobTicket.JobType == JobTypes.Maintenance || JobTicket.JobType == JobTypes.Inspection)
            {
                if (string.IsNullOrWhiteSpace(JobTicket.Description))
                    ModelState.AddModelError("JobTicket.Description", "Please provide a description.");

                JobTicket.FiberPlan = null;
            }

            // Maintenance jobs don't collect client contact info — clear whatever was
            // submitted (in case the client tampered with the request) instead of
            // requiring it. Every other job type still requires Client Full Name and
            // Primary Number.
            if (JobTicket.JobType == JobTypes.Maintenance)
            {
                JobTicket.ClientFullName = string.Empty;
                JobTicket.PrimaryNumber = string.Empty;
                JobTicket.SecondaryNumber = null;
            }
            else
            {
                if (string.IsNullOrWhiteSpace(JobTicket.ClientFullName))
                    ModelState.AddModelError("JobTicket.ClientFullName", "Client full name is required.");

                if (string.IsNullOrWhiteSpace(JobTicket.PrimaryNumber))
                    ModelState.AddModelError("JobTicket.PrimaryNumber", "Primary number is required.");
                else if (!System.Text.RegularExpressions.Regex.IsMatch(JobTicket.PrimaryNumber, @"^[0-9+\-\s()]{7,20}$"))
                    ModelState.AddModelError("JobTicket.PrimaryNumber", "Enter a valid contact number.");

                if (!string.IsNullOrWhiteSpace(JobTicket.SecondaryNumber) &&
                    !System.Text.RegularExpressions.Regex.IsMatch(JobTicket.SecondaryNumber, @"^[0-9+\-\s()]{7,20}$"))
                    ModelState.AddModelError("JobTicket.SecondaryNumber", "Enter a valid contact number.");
            }

            if (!SelectedEmployeeIds.Any())
                ModelState.AddModelError(string.Empty, "Please assign at least one field technician.");

            if (SelectedEmployeeIds.Any() && LeaderEmployeeId == 0)
                ModelState.AddModelError(string.Empty, "Please choose who will lead this job.");

            if (LeaderEmployeeId != 0 && !SelectedEmployeeIds.Contains(LeaderEmployeeId))
                ModelState.AddModelError(string.Empty, "The leader must be one of the assigned field technicians.");

            // Only active Field Technicians may be assigned, even if the request was tampered with.
            List<int> validEmployeeIds = new();
            if (SelectedEmployeeIds.Any())
            {
                validEmployeeIds = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician && SelectedEmployeeIds.Contains(e.EmployeeId))
                    .Select(e => e.EmployeeId)
                    .ToListAsync();

                if (SelectedEmployeeIds.Except(validEmployeeIds).Any())
                    ModelState.AddModelError(string.Empty, "Job tickets can only be assigned to active Field Technicians.");
            }

            if (!ModelState.IsValid)
            {
                FieldTechnicianList = await _context.Employees
                    .Where(e => e.IsActive && e.RoleType == RoleType.FieldTechnician)
                    .OrderBy(e => e.FullName)
                    .ToListAsync();
                NextTicketNumber = await GenerateTicketNumberAsync();
                return Page();
            }

            JobTicket.TicketNumber = await GenerateTicketNumberAsync();
            JobTicket.Status = JobTicketStatuses.Pending;

            _context.JobTickets.Add(JobTicket);
            await _context.SaveChangesAsync(); // generates JobTicket.JobTicketID

            foreach (var employeeId in SelectedEmployeeIds)
            {
                _context.JobTicketAssignments.Add(new JobTicketAssignment
                {
                    JobTicketID = JobTicket.JobTicketID,
                    EmployeeID = employeeId,
                    IsLeader = employeeId == LeaderEmployeeId,
                    AssignedDate = DateTime.Now
                });
            }

            await _context.SaveChangesAsync();

            return RedirectToPage("Index");
        }

        private async Task<string> GenerateTicketNumberAsync()
        {
            var count = await _context.JobTickets.CountAsync();
            return $"JOB-{DateTime.Now:yyyy}-{(count + 1):D4}";
        }
    }
}
